// SPDX-FileCopyrightText: 2025 ghostflyby
// SPDX-License-Identifier: Apache-2.0
#if os(macOS)
  import Distributed
  import SwiftXPC

  /// Errors produced while dispatching an inbound invocation on the service
  /// side. Surfaces to the caller inside a `.throwError` reply envelope;
  /// `targetExecutionFailed` additionally covers errors thrown by the target
  /// method itself when its typed error is not marshalable.
  @available(macOS 15, *)
  @XPCMarshal
  public enum XPCDispatchError: Error, Sendable, Equatable {
    case unknownActor(XPCActorID)
    case unknownTarget(String)
    case missingTargetMetadata(String)
    case targetExecutionFailed(String)
    case missingInvocationResult
    case unsupportedProtocolVersion(expected: UInt64, actual: UInt64)
  }

  /// Per-method metadata generated by `@XPCService`. Currently records the
  /// typed-throws error type of each distributed method so the client can
  /// decode errors the compiler erased to `any Error`.
  @available(macOS 15, *)
  public struct XPCDistributedTargetMetadata {
    public let thrownErrorType: (any (XPCMarshal & Error).Type)?

    public init(
      thrownErrorType: (any (XPCMarshal & Error).Type)? = nil
    ) {
      self.thrownErrorType = thrownErrorType
    }
  }

  @available(macOS 15, *)
  func parseTargetIdentifier(_ identifier: String) -> String? {
    // The class-name terminator `C` must be found left-to-right: return-type
    // components later in the mangled name (e.g. `AA0C4Note`) may also contain
    // a `C` followed by a digit, and a rightmost scan would mis-parse there.
    var searchStart = identifier.startIndex
    while let cIndex = identifier[searchStart...].firstIndex(of: "C") {
      if let parsed = parseMethodSuffix(identifier, from: identifier.index(after: cIndex)) {
        return parsed
      }
      searchStart = identifier.index(after: cIndex)
    }
    return nil
  }

  private func parseMethodSuffix(_ identifier: String, from start: String.Index) -> String? {
    var pos = start
    var digits = ""
    while pos < identifier.endIndex, identifier[pos].isNumber {
      digits.append(identifier[pos])
      pos = identifier.index(after: pos)
    }
    guard let baseLen = Int(digits),
      identifier.distance(from: pos, to: identifier.endIndex) >= baseLen
    else { return nil }
    let baseEnd = identifier.index(pos, offsetBy: baseLen)
    let baseName = String(identifier[pos..<baseEnd])
    pos = baseEnd
    var labels: [String] = []
    while pos < identifier.endIndex, identifier[pos].isNumber {
      digits = ""
      while pos < identifier.endIndex, identifier[pos].isNumber {
        digits.append(identifier[pos])
        pos = identifier.index(after: pos)
      }
      guard let labelLen = Int(digits),
        identifier.distance(from: pos, to: identifier.endIndex) >= labelLen
      else { return nil }
      let labelEnd = identifier.index(pos, offsetBy: labelLen)
      let label = String(identifier[pos..<labelEnd])
      // Type components (e.g. an unsubstituted struct return type) also start
      // with a digit; real parameter labels begin lowercase or with `_`.
      guard let first = label.first, first.isLowercase || first == "_" else { break }
      labels.append(label)
      pos = labelEnd
    }
    if labels.isEmpty { return "\(baseName)()" }
    return "\(baseName)(\(labels.map { "\($0):" }.joined()))"
  }

  /// Marks an actor whose distributed methods are dispatchable over XPC.
  /// Applied automatically by `@XPCService`.
  ///
  /// The table acts as a dispatch whitelist. An *empty* table opts into
  /// permissive dispatch: any distributed target the actor exposes is accepted,
  /// but typed-throws error metadata is unavailable, so thrown errors must
  /// conform to `XPCMarshal` to be decodable by the caller.
  @available(macOS 15, *)
  public protocol XPCDistributedTargetMetadataProviding: DistributedActor
  where ActorSystem == XPCDistributedActorSystem, ID == XPCActorID {
    static var xpcDistributedTargetMetadata: [String: XPCDistributedTargetMetadata] { get }
  }

  @attached(
    extension,
    conformances: XPCDistributedTargetMetadataProviding, XPCExportableActor,
    names: named(xpcDistributedTargetMetadata))
  public macro XPCService() = #externalMacro(module: "SwiftXPCMacros", type: "XPCServiceMacro")

#endif
